# Generated by Django 4.0.3 on 2022-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
