# Generated by Django 4.0.3 on 2022-09-23 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0002_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
