# Generated by Django 4.0.3 on 2022-09-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0006_purchase_purchaseproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproducts',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employee'),
        ),
    ]
