# Generated by Django 4.0.3 on 2022-10-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0011_alter_expenses_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproducts',
            old_name='weight',
            new_name='weights',
        ),
    ]
