# Generated by Django 4.0.3 on 2022-10-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0012_rename_weight_purchaseproducts_weights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproducts',
            old_name='weights',
            new_name='weight',
        ),
    ]
