# Generated by Django 4.0.3 on 2022-10-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0013_rename_weights_purchaseproducts_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproducts',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_fk', to='lsmsApp.employeeproducts'),
        ),
        migrations.AlterField(
            model_name='purchaseproducts',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_fk', to='lsmsApp.purchase'),
        ),
    ]
