# Generated by Django 4.0.3 on 2022-10-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0018_remove_customuser_gender_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproducts',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employee'),
        ),
    ]
