# Generated by Django 4.0.3 on 2022-10-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0022_remove_products_product_id_products_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproducts',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='admin',
        ),
    ]
