# Generated by Django 4.0.3 on 2022-10-27 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0023_remove_invoiceproducts_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('total_amount', models.FloatField(max_length=15)),
                ('amount_paid', models.FloatField(max_length=15)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'In-progress'), ('2', 'Done')], default=0, max_length=2)),
                ('payment', models.CharField(choices=[('0', 'Unpaid'), ('1', 'Paid')], default=0, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employee')),
            ],
            options={
                'verbose_name_plural': 'List of Employee Invoices',
            },
        ),
        migrations.CreateModel(
            name='BillProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=15)),
                ('weight', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_fk', to='lsmsApp.bill')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billproducts_fk', to='lsmsApp.products')),
            ],
            options={
                'verbose_name_plural': 'List of Invoice Products',
            },
        ),
    ]
