# Generated by Django 4.0.3 on 2022-10-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0024_bill_billproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employee'),
        ),
    ]
