# Generated by Django 4.0.3 on 2022-10-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0025_alter_bill_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_fk2', to='lsmsApp.bill'),
        ),
    ]
