# Generated by Django 4.0.3 on 2022-10-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0026_remove_bill_employee_employee_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employee'),
        ),
    ]
