# Generated by Django 4.0.3 on 2022-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0030_collecteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact',
        ),
        migrations.AddField(
            model_name='invoice',
            name='collecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.collecteur'),
        ),
    ]
