# Generated by Django 4.0.3 on 2022-11-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0031_remove_invoice_client_remove_invoice_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='position',
        ),
    ]
