# Generated by Django 4.0.3 on 2022-11-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0033_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='contact',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.client'),
        ),
    ]
