# Generated by Django 4.0.3 on 2022-11-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0035_sales_salesproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='status',
            new_name='regulation',
        ),
    ]
