# Generated by Django 4.0.3 on 2022-11-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0036_rename_status_purchase_regulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='status',
            new_name='state',
        ),
    ]
