# Generated by Django 4.0.3 on 2022-11-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0037_rename_status_sales_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='state',
            new_name='ranking',
        ),
    ]
