# Generated by Django 4.0.3 on 2022-11-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0039_rename_ranking_sales_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproducts',
            name='employee_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lsmsApp.employeeproducts'),
        ),
    ]
