# Generated by Django 4.0.3 on 2022-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0040_billproducts_employee_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproducts',
            name='employee_products',
        ),
    ]
