# Generated by Django 4.0.3 on 2022-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmsApp', '0041_remove_billproducts_employee_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
